remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  '@nll/datum on GitHub':
    - 'https://github.com/nullpub/datum#readme'
